# Assignment 3

Question 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [1]:
import numpy as np
ar = np.arange(2,51,3)
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Question 2

Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [3]:
ar1,ar2 = (list(map(int,input().split())) for i in range(2))
ar1 = np.array(ar1)
ar2 = np.array(ar2)
print(np.concatenate((ar1,ar2)))
print(np.sort(np.concatenate((ar1,ar2))))

3 6 9
2 4 6
[3 6 9 2 4 6]
[2 3 4 6 6 9]


Question 3

Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
ar = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
print(ar.shape,ar.size)

(3, 3) 9


Question 4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims


In [4]:

   # To convert a 1D array into a 2D array, we can use reshape(a, newshape, order='C').  

ar = np.array([ [1,2,3,4,5,6,7,8,9] ])

print(ar,ar.shape) 

print()

ar = ar.reshape(3,3) 

print(ar,ar.shape)

[[1 2 3 4 5 6 7 8 9]] (1, 9)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


Question 5

Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()


In [5]:
import numpy as np
ar1 = np.array([ [1,5,3], [4,2,6], [7,8,9] ])
ar2 = np.array([ [10,11,12], [13,14,15], [16,17,18,] ])
#vertically stacking 
Vstack = np.vstack([ar1, ar2])
#horizonatally stacking 
Hstack = np.hstack([ar1, ar2])
print('Vertical Stacking:\n',Vstack)
print('Horizontal Stacking:\n',Hstack)



Vertical Stacking:
 [[ 1  5  3]
 [ 4  2  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Horizontal Stacking:
 [[ 1  5  3 10 11 12]
 [ 4  2  6 13 14 15]
 [ 7  8  9 16 17 18]]


Question 6

How to get unique items and counts of unique items?


In [9]:
list1 = [1,3,1,9,4,6,6,9,7]
list1 = list(set(list1))
print(list1)
print()
print(len(list1))



[1, 3, 4, 6, 7, 9]

6
